### PR TITLE
rm optional trailing commas

### PR DESCRIPTION
**Pull request by robitalec**
Cleaned up `data.table` sections by removing the trailing commas which are optional ([see points 2, 3](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html#SmallerDiffs)). 

I think this better represents `data.table` syntax. 
Only the `.Rmd` file was changed.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Not bad! Thanks for the PR.  

I usually keep them in the code I write just to remind myself about `dt[i, j, by]` but I concur.

Let me run this by @mattdowle @arunsrinivasan @jangorecki @MichaelChirico -- any views?

**Comment by MichaelChirico** [comment]
Definitely stylistic... `, ` is equivalent to to `missing(j)` which is all that's ever tested internally:

```
f = function(x, y) {missing(y)}
f(1)
# [1] TRUE
f(1, )
# [1] TRUE
```

Speaking for myself & my own code, I omit the trailing comma & it drives me nuts to use `data.frame`-alike `[` methods where it's required when seemingly unnecessary (Python/Matlab `:` auto-slicing would be nice sometimes).

I also sometimes leave a trailing space before the end bracket or paren... just looks prettier on occasion I reckon.

**Comment by eddelbuettel** [comment]
Thanks again. Made one or two small tweaks and re-rendered the pdf.

**Comment by MichaelChirico** [comment]
out of curiosity, FWIW, no such trailing comma found in `data.table` source:

```
grep "^\s*[^#]*\[[^,]*[,]\s*\]" R/*

R/groupingsets.R:  sets = lapply((2L^n):1L, function(j) by[keepBool[j, ]])
R/last.R:    } else if (is.data.frame(x)) return(x[NROW(x),])
R/last.R:    } else if (is.data.frame(x)) return(x[1L,])
```

**Comment by robitalec** [comment]
Great! Thanks @eddelbuettel and @MichaelChirico.

**Pull request merged**
