### PR TITLE
Added to `str(cw)` to show that Diet and Time are now factors.

### PR DESCRIPTION
**Pull request by saghirb**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Not sure about the 3rd commit. `data.table` lives by the `dt[i, j, by]` mantra and I want to talk about i, j and by.

Open to reworking the para, less sure I want to remove it.

**Comment by saghirb** [comment]
I think that we can leave it if the by can be changed to `by=.(Diet, Time)`? Is that OK?

**Comment by eddelbuettel** [comment]
Ye, that is a good idea.  I also glanced at the text and there are other sections dedicated to `j`.  But I still think it is important to show `j` as a reduction.

**Comment by eddelbuettel** [comment]
There is one error at the end. I had to add the latex trick `\phantom{XX}` for some vertical spacing.  It now lacks an empty line before `## Interpretation` so that is no longer a header.

**Comment by saghirb** [comment]
Strange as when I knit it I don't get an error (after I deleted the `\phantom{XX}`)... The last page is as follows:

nophantom

**Comment by eddelbuettel** [comment]
Well yes -- deleting the `\phantom{XX}` is one fix, of course.  But the previous pdf (which I guess is still the one in this PR) has that minor issue.

Can you revert the removal of the section and maybe change as discussed to group over two columns instead?

**Comment by saghirb** [comment]
Indeed the PDF in the PR still has the issue that you raised. I will update and double check before my next pull request.

I have reverted the change and updated the `by` as above. As is expected it shows all the summaries for all combinations of Diet and Time (48 rows). Is there a nice way to limit this to a select few rows given that the `i`part comes afterwards?

**Comment by eddelbuettel** [comment]
Ah, right. I think I had that issue too at times and then decided to use simpler code to not have 48 rows.  

Maybe a simple `head()` ? Or a training `[1:10]` ?   Or back to just one group?

**Comment by saghirb** [comment]
The following does it `options(datatable.print.nrows=##)` :)

**Comment by eddelbuettel** [comment]
Ah yes :)   We should mention that the display is truncated though.

**Comment by saghirb** [comment]
I think that I managed to get things into shape. If not, don't hesitate to let me know.

**Pull request merged**
